[package]
name = "rusty-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.28.1"
sysinfo = "0.33.1"
tokio = { version = "1.43.0", features = ["full"] }
anyhow = "1.0.95"
chrono = "0.4.39"
rand = "0.9.2"
