[package]
name = "rusty-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.19"
pollster = "0.3"
log = "0.4"
env_logger = "0.11"
bytemuck = { version = "1.14", features = ["derive"] }
futures-intrusive = "0.5"
half = { version = "2.7.1", features = ["std"] }

